rec_obj = audiorecorder;
rec_duration = 2;
disp('Begin Speaking...');
recordblocking(rec_obj,rec_duration);
disp('End of Recording');
y = getaudiodata(rec_obj);
subplot(2,1,1);
plot(y);
title('Original Speech');
xlabel('Time');
ylabel('Amplitude');
fs = 100;
p = fft(y);
n = length(p);
f = (0:n-1)*fs/n;
power = abs(y).^2/n;
subplot(2,1,2);
plot(f,power);
title('Speech Spectrum');
xlabel('Frequency');
ylabel('Amplitude');
